"""Small, explicit learning gates before introducing larger policies."""

from .baselines import BaselineEvaluation, evaluate_baselines
from .decision import build_act_decision_report
from .full_dataset import (
    ImageSignalStatus,
    Lead3TrainingCache,
    SmallModelComparison,
    SmallModelConfig,
    SmallModelKind,
    SmallModelRun,
    build_lead3_training_cache,
    build_small_model,
    classify_image_signal,
    cross_episode_image_indices,
    evaluate_image_ablation,
    load_small_model_comparison,
    train_small_models,
)
from .tiny_model import (
    TinyModelConfig,
    TinyOverfitResult,
    build_memorization_subset,
    run_tiny_overfit,
)
from .oracle_distillation import (
    ORACLE_MEMORIZATION32_ROWS,
    OracleCloneKind,
    OracleDistillationConfig,
    OracleDistillationResult,
    OracleLearningRateSchedule,
    OracleResidualAnalysisResult,
    OracleTrainingRows,
    analyze_oracle_residuals,
    build_oracle_clone_model,
    build_oracle_features,
    count_oracle_command_safety_violations,
    distill_oracle_policy,
    oracle_learning_rate,
    oracle_feature_schema,
    oracle_recovery_weighted_loss,
    oracle_training_row_indices,
)
__all__ = [
    "BaselineEvaluation",
    "ImageSignalStatus",
    "Lead3TrainingCache",
    "SmallModelComparison",
    "SmallModelConfig",
    "SmallModelKind",
    "SmallModelRun",
    "TinyModelConfig",
    "TinyOverfitResult",
    "OracleCloneKind",
    "OracleLearningRateSchedule",
    "OracleTrainingRows",
    "ORACLE_MEMORIZATION32_ROWS",
    "OracleDistillationConfig",
    "OracleDistillationResult",
    "OracleResidualAnalysisResult",
    "build_memorization_subset",
    "build_lead3_training_cache",
    "build_act_decision_report",
    "build_small_model",
    "build_oracle_clone_model",
    "build_oracle_features",
    "analyze_oracle_residuals",
    "count_oracle_command_safety_violations",
    "oracle_training_row_indices",
    "oracle_learning_rate",
    "oracle_feature_schema",
    "oracle_recovery_weighted_loss",
    "classify_image_signal",
    "cross_episode_image_indices",
    "evaluate_baselines",
    "evaluate_image_ablation",
    "load_small_model_comparison",
    "run_tiny_overfit",
    "train_small_models",
    "distill_oracle_policy",
]
